version: "3.3"

services:
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./config/:/mosquitto/config/
      - ./log/:/mosquitto/log/
      - data:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001

volumes:
  data: ~

