version: "3.3"

services:
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./config/:/mosquitto/config/
      - ./log/:/mosquitto/log/
      - data:/mosquitto/data/
    ports:
        - "12101:12101" 
    devices:
        - "/dev/snd:/dev/snd"
    command: --user-profiles /profiles --profile es
      - 1883:1883
      - 9001:9001

volumes:
  data: ~
