version: '3'

services:
 rhasspy:
    image: "rhasspy/rhasspy"
    container_name: rhasspy
    restart: unless-stopped
    volumes:
        - "./rhasspy/profiles:/profiles"
        - "/etc/localtime:/etc/localtime:ro"
    ports:
        - "12101:12101" 
    devices:
        - "/dev/snd:/dev/snd"
    command: --user-profiles /profiles --profile es
